<a href="https://colab.research.google.com/github/aliceechen1206/sales-predictions/blob/main/Numpy_Bakery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
price = [2, 1, 10]
type(price)

list

In [59]:
quantity = [17, 40, 1]
type(quantity)

list

In [60]:
# price * quantity

In [61]:
import numpy as np

In [62]:
price_array = np.array(price)
quantity_array = np.array(quantity)
type(price_array)

numpy.ndarray

In [63]:
price_array * quantity_array

array([34, 40, 10])

In [64]:
cost_array = np.array([0.25, 0.50, 5.00])

In [65]:
profit_array = price_array - cost_array
print(profit_array)


[1.75 0.5  5.  ]


In [66]:
profit_array > 2.00


array([False, False,  True])

In [67]:
price_array = price_array + [7]
print(price_array)


[ 9  8 17]


In [68]:
# Just fixing the mistake
price_array = price_array - [7]
# The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)


[ 2  1 10  7]


In [69]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)



[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [70]:
print(price_array.dtype)


float64


In [71]:
price_array = np.delete(price_array, -1)
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4. ]


In [72]:
price_array[2] = 12
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4. ]


1) OPEN THE NOTEBOOK YOU CREATED DURING THE PREVIOUS LESSON: INTRO TO NUMPY ARRAYS!

If you did not start this notebook, please go back to the INTRO TO NUMPY ARRAYS lesson and follow along with the code before starting this task!

You will start this task where the demonstration code left off.  

# The Assignment Starts Here

2) Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.  You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantity_sold_array from 40 to 39.

In [73]:
quantity_sold = [17, 40, 1]
type(quantity_sold)
quantity_sold_array = np.array(quantity_sold)
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [74]:
quantity_sold = [17, 40, 1]
type(quantity_sold)
quantity_sold_array = np.array(quantity_sold)
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])
quantity_sold_array [1] = 39
print (quantity_sold_array)

[17 39  1  2  3 16  5]


3) Determine the amount of money collected from the sale of each item at the bake sale.  

In [75]:
price = [2, 1, 12]
type(price)
quantity_sold = [17, 40, 1]
type(quantity_sold)
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)
price_array = np.append(price_array, [7, 4.50, 3, 4])
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
quantity_sold_array [1] = 39
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?

In [76]:
quantity_leftover = [0, 0, 2, 1, 6, 0, 2]
quantity_leftover_array = np.array (quantity_leftover)

5) The club decides to sell the leftover items at half price and everything quickly sells out!  Determine how much money was collected from the clearance sale. 

In [77]:
discounts = np.array([0,0,.50,.50,.50,0,.50])
price_array
discounted_prices = price_array - price_array*discounts
discounted_prices
np.sum(discounted_prices * quantity_leftover_array).round(2)

33.0

6) How much total money was collected from the bake sale (including the sale of full price and clearance items)?

Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!

In [83]:
np.sum ((price_array * quantity_sold_array) + (discounted_prices * quantity_leftover_array)).round (2)

213.5